version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3030:3030
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - rentalx
    links:
      - "db:database"
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentalx
    environment:
      POSTGRES_USER: rentalx
      POSTGRES_PASSWORD: test
      POSTGRES_DB: rentalx


volumes: 
  pgdata:
    driver: local
networks:
  rentalx:
    driver: bridge
