version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3030:3030
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - rentalx
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - data:/data/db
    environment:
      POSTGRES_PASSWORD: test
    networks:
      - rentalx

volumes: 
  data:
    name: database
networks:
  rentalx:
    driver: bridge